version: "3.9"

services:
  backend:
    build: ./backend
    container_name: codigo-backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 2
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data
    environment:
      DJANGO_SECRET_KEY: super-secret-key
      DEBUG: "False"
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: codigo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
